---
version: 2
models:
  - name: base_census
    columns:
      - name: patient_num
        tests:
          - not_null
          - unique
      - name: start_date
        tests: [not_null]
      - name: latitude
        tests: [not_null]
      - name: longitude
        tests: [not_null]
  - name: base_demo
    columns:
      - name: patient_num
        tests:
          - not_null
          - unique
      - name: mrn
        tests:
          - not_null
          - unique
      - name: vital_status
        tests: [not_null]
      - name: birth_date
        tests: [not_null]
  - name: base_efi
    columns:
      - name: mrn
        tests:
          - not_null
  - name: base_encounters
    tests:
      - unique:
          column_name: "(patient_num || '-' || encounter_num)"
    columns:
      - name: patient_num
        tests: [not_null]
  - name: base_emr
    columns:
      - name: patient_num
        tests: [not_null]
      - name: encounter_num
        tests: [not_null]
      - name: concept
        tests: [not_null]
  - name: base_patients
    columns:
      - name: patient_num
        tests:
          - not_null
          - unique
sources:
  - name: emr
    schema: rybarnar_dbt_emr
    tables:
      - name: census
        identifier: stg_census
      - name: emr
        identifier: stg_emr
      - name: demo
        identifier: stg_demo
      - name: encounters
        identifier: stg_encounters
      - name: efi
        identifier: stg_efi
