---
version: 2
sources:
  - name: emr
    schema: rybarnar_dbt_emr
    tables:
      - name: census
        identifier: stg_census
      - name: emr
        identifier: stg_emr
      - name: demo
        identifier: stg_demo
